[package]
name = "links"
version = "0.2.0"
authors = ["Tobias Moldan <tobias.moldan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
