DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS redirect;

CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    pw_hash TEXT NOT NULL
);

CREATE TABLE redirect (
    path TEXT PRIMARY KEY NOT NULL,
    user_id INTEGER NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    url TEXT NOT NULL,
    CONSTRAINT fk_user_id
        FOREIGN KEY (user_id) 
        REFERENCES user (id) 
        ON DELETE CASCADE
);